# Generated by Django 5.1.4 on 2025-01-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferdetails",
            name="bank_account_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transferdetails",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
