# Generated by Django 4.2.4 on 2025-01-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core_root_api_transactions",
            "0002_alter_transferdetails_bank_account_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transferdetails",
            name="date_created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
