# Generated by Django 5.1.4 on 2025-02-14 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_transactions", "0003_transferdetails_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferdetails",
            name="amount",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
