# Generated by Django 5.1.4 on 2025-01-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("card_number", models.CharField(blank=True, max_length=25, null=True)),
                ("card_date", models.DateField(auto_now_add=True, null=True)),
                ("card_cvv", models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
