# Generated by Django 5.1.4 on 2025-01-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_card_management", "0002_cardmanagement_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardmanagement",
            name="card_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
